# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ClinicStudy.py
# Created on: 2020-05-07 22:19:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: ClinicStudy <Study_Area_Block_Groups> <Clients> <City_Bus_Stops> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Study_Area_Block_Groups = arcpy.GetParameterAsText(0)

Clients = arcpy.GetParameterAsText(1)

City_Bus_Stops = arcpy.GetParameterAsText(2)

# Local variables:
Output_direction_raster = ""
density = "C:\\EsriPress\\GTKArcGIS\\Chapter20\\MyData\\density"
distance = "C:\\EsriPress\\GTKArcGIS\\Chapter20\\MyData\\distance"
ext_density = "C:\\EsriPress\\GTKArcGIS\\Chapter20\\MyData\\ext_density"
recl_density = "C:\\EsriPress\\GTKArcGIS\\Chapter20\\MyData\\recl_density"
recl_distance = "C:\\EsriPress\\GTKArcGIS\\Chapter20\\MyData\\recl_distance"
Study_Area_Block_Groups__2_ = Study_Area_Block_Groups
Study_Area_Block_Groups__3_ = Study_Area_Block_Groups__2_
children = "C:\\EsriPress\\GTKArcGIS\\Chapter20\\MyData\\children"
ext_children = "C:\\EsriPress\\GTKArcGIS\\Chapter20\\MyData\\ext_children"
recl_children = "C:\\EsriPress\\GTKArcGIS\\Chapter20\\MyData\\recl_children"
final = "c:\\gis\\modelbuilder\\scratch.gdb\\recl_densit1"

# Process: Euclidean Distance
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = ""
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-122.846006949189 38.3521100468406 -122.565303939558 38.5565739606092"
arcpy.gp.EucDistance_sa(City_Bus_Stops, distance, "2640", "100", Output_direction_raster, "PLANAR")
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1

# Process: Point Density
arcpy.gp.PointDensity_sa(Clients, "", density, "100", "Circle 2000 MAP", "SQUARE_MAP_UNITS")

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa(density, distance, ext_density)

# Process: Reclassify
arcpy.gp.Reclassify_sa(ext_density, "VALUE", "0 37.714375 1;37.714375 113.143120 2;113.143120 221.849258 3;221.849258 372.706757 4;372.706757 550.186157 5;550.186157 778.690918 6;778.690918 1129.212769 7", recl_density, "DATA")

# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(distance, "VALUE", "0 3863.935791 7;3863.935791 8714.356445 6;8714.356445 13572.398438 5;13572.398438 18348.025391 4;18348.025391 23244.138672 3;23244.138672 28768.906250 2;28768.906250 39855.363281 1", recl_distance, "DATA")

# Process: Add Field
arcpy.AddField_management(Study_Area_Block_Groups, "PERC_UNDER5", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Study_Area_Block_Groups__2_, "PERC_UNDER5", "[AGE_UNDER5] / [POP2000]", "VB", "")

# Process: Polygon to Raster
arcpy.PolygonToRaster_conversion(Study_Area_Block_Groups__3_, "PERC_UNDER5", children, "CELL_CENTER", "NONE", "100")

# Process: Extract by Mask (2)
arcpy.gp.ExtractByMask_sa(distance, children, ext_children)

# Process: Reclassify (3)
arcpy.gp.Reclassify_sa(ext_children, "VALUE", "0 2531.797852 1;2531.797852 5632.051270 2;5632.051270 8829.496094 3;8829.496094 12185.237305 4;12185.237305 15915.401367 5;15915.401367 20242.777344 6;20242.777344 27435.742188 7", recl_children, "DATA")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("\"%recl_density%\" + \"%recl_distance%\" + \"%recl_children%\"", final)

