# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# make_streamlines.py
# Created on: 2020-05-06 17:38:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: make_streamlines <Input_Surface_Raster> <Workspace> <Extent> <Cell_Size> <Output_Flow_Direction> <Output_Accumulation_Raster> <SQL_Expression> <Hyro_Network> <StreamLink> <StreamLines> 
# Description: 
# Creates a hyrographic network from a DEM based on a minimum area threshold
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Surface_Raster = arcpy.GetParameterAsText(0)

Workspace = arcpy.GetParameterAsText(1)

Extent = arcpy.GetParameterAsText(2)

Cell_Size = arcpy.GetParameterAsText(3)
if Cell_Size == '#' or not Cell_Size:
    Cell_Size = "MAXOF" # provide a default value if unspecified

Output_Flow_Direction = arcpy.GetParameterAsText(4)
if Output_Flow_Direction == '#' or not Output_Flow_Direction:
    Output_Flow_Direction = "C:\\GIS\\ModelBuilder\\scratch.gdb\\OutputFlowDirection" # provide a default value if unspecified

Output_Accumulation_Raster = arcpy.GetParameterAsText(5)
if Output_Accumulation_Raster == '#' or not Output_Accumulation_Raster:
    Output_Accumulation_Raster = "C:\\GIS\\ModelBuilder\\scratch.gdb\\OutputAccumulationRaster" # provide a default value if unspecified

SQL_Expression = arcpy.GetParameterAsText(6)
if SQL_Expression == '#' or not SQL_Expression:
    SQL_Expression = "VALUE <100" # provide a default value if unspecified

Hyro_Network = arcpy.GetParameterAsText(7)
if Hyro_Network == '#' or not Hyro_Network:
    Hyro_Network = "C:\\GIS\\ModelBuilder\\scratch.gdb\\HydroNetwork" # provide a default value if unspecified

StreamLink = arcpy.GetParameterAsText(8)
if StreamLink == '#' or not StreamLink:
    StreamLink = "C:\\GIS\\ModelBuilder\\scratch.gdb\\StreamLink" # provide a default value if unspecified

StreamLines = arcpy.GetParameterAsText(9)
if StreamLines == '#' or not StreamLines:
    StreamLines = "C:\\GIS\\ModelBuilder\\scratch.gdb\\StreamT_StreamL1" # provide a default value if unspecified

# Local variables:
Output_drop_raster = ""

# Process: Flow Direction
tempEnvironment0 = arcpy.env.extent
arcpy.env.extent = Extent
tempEnvironment1 = arcpy.env.cellSize
arcpy.env.cellSize = Cell Size
tempEnvironment2 = arcpy.env.workspace
arcpy.env.workspace = "C:\\Users\\angul\\Documents\\ArcGIS\\Packages\\NAD1022-L3.4-ModelBuilder_7E236F45-450C-444A-AF46-1ECE21BB4FD7\\v103\\demo_data.gdb"
arcpy.gp.FlowDirection_sa(Input_Surface_Raster, Output_Flow_Direction, "NORMAL", Output_drop_raster, "D8")
arcpy.env.extent = tempEnvironment0
arcpy.env.cellSize = tempEnvironment1
arcpy.env.workspace = tempEnvironment2

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(Output_Flow_Direction, Output_Accumulation_Raster, "", "FLOAT", "D8")

# Process: Set Null
arcpy.gp.SetNull_sa(Output_Accumulation_Raster, Output_Accumulation_Raster, Hyro_Network, SQL_Expression)

# Process: Stream Link
arcpy.gp.StreamLink_sa(Hyro_Network, Output_Flow_Direction, StreamLink)

# Process: Stream to Feature
arcpy.gp.StreamToFeature_sa(StreamLink, Output_Flow_Direction, StreamLines, "SIMPLIFY")

